Refactoring administrator page
martadiachok/EasyRest-Testing pull request #21
Opened 2022-08-11 08:40 UTC by vadymtsehelny

2022-08-11 11:43 UTC, martadiachok commented on src/main/java/com/easyrest/facade/AdministratorOperationsFacade.java
> +    WebDriver driver;
should be private

2022-08-12 05:26 UTC, ViktoriaMilkevich requested changes

2022-08-12 05:26 UTC, ViktoriaMilkevich commented on src/main/java/com/easyrest/facade/AdministratorOperationsFacade.java
> +    WebDriver driver;
Why default access modifier? Should be private
Your driver is opened for any method within the package.

2022-08-12 05:26 UTC, ViktoriaMilkevich commented on src/main/java/com/easyrest/pages/administratorPanel/AssignedWaiterOrders.java
> +public class AssignedWaiterOrders extends AdministratorPage {
You should not use inheritance here

2022-08-12 14:52 UTC, dmatsev approved these changes

2022-08-12 15:40 UTC, Zeicks approved these changes

2022-08-15 11:32 UTC, ViktoriaMilkevich approved these changes

2022-08-15 14:27 UTC, martadiachok approved these changes

2022-08-15 14:43 UTC, merged